workflows:
  ios:
    name: iOS Workflow
    platform: ios
    environment:
      node: '22.12.0'  
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          npx react-native run-ios --configuration Release
      - name: Run tests (optional)
        script: |
          npx jest
      - name: Build IPA
        script: |
          xcodebuild archive -workspace ios/YourProject.xcworkspace -scheme ludo -archivePath $HOME/build/ludo.xcarchive
    artifacts:
      - $HOME/build/ludo.xcarchive
      - $HOME/build/ludo.ipa
