workflows:
  ios:
    name: iOS Workflow
    environment:
      node: '22.12.0'  
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          # Build the iOS app using xcodebuild
          xcodebuild -workspace ios/ludo.xcworkspace -scheme ludo -configuration Release -sdk iphoneos
      - name: Run tests (optional)
        script: |
          npx jest
      - name: Build IPA
        script: |
          xcodebuild archive -workspace ios/ludo.xcworkspace -scheme ludo -archivePath $HOME/build/ludo.xcarchive
    artifacts:
      - $HOME/build/ludo.xcarchive
      - $HOME/build/ludo.ipa
