workflows:
  ios:
    name: iOS build
    platform: ios
    xcode: latest
    build:
      scripts:
        - name: Install dependencies
          script: |
            npm install
            npx pod-install ios
        - name: Build iOS app
          script: |
            npx react-native run-ios --configuration Release
    test:
      name: Run tests
      script: npx jest
    publish:
      name: Deploy to App Store
      script: |
        fastlane ios release
